GET https://avia-terminal.herokuapp.com/avian/passengers


###
GET https://avia-terminal.herokuapp.com/avian/passengers

###
GET https://avia-terminal.herokuapp.com/avian/getallbaggage


###
GET https://avia-terminal.herokuapp.com/avian/passengers/search?firstName=Petrov&secondName=Ivan
###

GET https://avia-terminal.herokuapp.com/avian/baggagebyowner/3
###

GET https://avia-terminal.herokuapp.com/avian/totalbaggageweidht

###

GET https://avia-terminal.herokuapp.com/avian/passengersbyflight/3
###



POST https://avia-terminal.herokuapp.com/avian/save
Content-Type: application/json

{
  "flightId": 3,
  "firstName": "Salahov",
  "secondName": "Robert",
  "passportNumber": 934562323,
  "passengerOnBoard": true,
  "baggageOnBoard": false
}
###
DELETE https://avia-terminal.herokuapp.com/avian/deletepassenger/3

###

GET https://avia-terminal.herokuapp.com/avian/baggagebyid/3

###

GET http://127.0.0.1:8080/avian/totalbaggageweidht


###
